#!/bin/sh

trap "exit" TERM

# Checking if there are any USB devices in '/dev/bus/usb'. This is 
# because libusbx, a library used by fcserver will throw an error
# during init if this directory doesn't exist or has no contents.
# This error seems to occur only on linux, so I've made this workaround.
if [ -n "$(ls -A /dev/bus/usb 2>/dev/null)" ]
then
    echo "Starting fcsever..."
    ./fcserver config.json
else
    echo "ERROR: It seems that you haven't passed any USB devices to this container. fcserver needs at least one attached USB device to start."
    exit 1
fi
